#!/usr/bin/env bash

set -eu

ScriptDir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

# shellcheck source=../common.sh
. "${ScriptDir}/../common.sh"

BuildDir="$(getBuildDir)"

if [ -d "${BuildDir}" ]; then
    cmake --build "${BuildDir}" --target clean
fi
