#!/usr/bin/env bash

set -eu

ScriptDir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

# shellcheck source=../common.sh
. "${ScriptDir}/../common.sh"

InstallPrefix="${1:-${TINYGL_INSTALL_PREFIX:-${PROJECT_ROOT}/dist}}"

configureTinyGl
cmake --install "$(getBuildDir)" --prefix "${InstallPrefix}"
