#!/usr/bin/env bash

set -eu

ScriptDir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

# shellcheck source=../common.sh
. "${ScriptDir}/../common.sh"

"${ScriptDir}/../clean/clean"
"${ScriptDir}/../build/build"
